name: archive

on:
  schedule:
    - cron:  '5 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - run: |
        chmod +x ./archive.sh
        ./archive.sh
